const cmd = {
    cal: function(args) {},
    cd: function(args) {},
    cls: function(args) {},
    clear: function(args) {},
    date: function(args) {},
    dir: function(args) {},
    echo: function(args) {},
    find: function(args) {},
    help: function(args) {},
    hostname: function(args) {},
    ls: function(args) {},
    lynx: function(args) {},
    man: function(args) {},
    more: function(args) {},
    msg: function(args) {},
    pwd: function(args) {},
    sort: function(args) {},
    stat: function(args) {},
    tree: function(args) {},
    whatis: function(args) {},
    whoami: function(args) {}
}